name: fastapi-hello-world
region: fra
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: peterlada/fastapi-hello-world
    health_check:
      http_path: /
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    routes:
      - path: /
