name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        
    - name: Install uv
      run: pip install uv
        
    - name: Install dependencies
      run: |
        uv pip install .[dev]
        
    - name: Run tests
      run: pytest
        
    - name: Lint with ruff
      run: |
        uv pip install ruff
        ruff check .
        ruff format --check .
